### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gorillamoe**
Replace unmaintained rest.nvim with kulala.nvim.

### CODE REVIEW

**Comment by oysandvik94** [comment]
Thanks for the contribution! I was thinking though, would it make sense to reword the title to "Similar plugins" instead of "Alternatives", and mention both kulala and rest.nvim?

**Comment by oysandvik94** [comment]
@gorillamoe Sorry, I'm a bit new to doing PR's by fork, did you make a change according to my comment? I see this in the PR: "Add more commits by pushing to the [patch-1](https://github.com/gorillamoe/curl.nvim/tree/patch-1) branch on [gorillamoe/curl.nvim](https://github.com/gorillamoe/curl.nvim)." and I'm not sure if this means that the there are changes that are not present in the PR

**Comment by gorillamoe** [comment]
No, but Im going to push some changes in the next few minutes and then I'm going to report back here.

**Comment by oysandvik94** [comment]
Great! No rush of course, was just curious if I missed something

**Comment by gorillamoe** [comment]
@oysandvik94, pushed the changes.

**Review by oysandvik94 — APPROVED** [review]

**Comment by oysandvik94** [comment]
Thank you so much for your contribution!

**Pull request merged**
